// encoding: utf-8
= Better spool handling for Checkmk

This repository contains an link:https://github.com/checkmk/checkmk[Checkmk^] agent plugin and bakery configuration interface (JSON config can be easily generated by other tools) for a safer and more reliable handling of link:https://docs.checkmk.com/latest/en/spool_directory.html[spool files^].

* A buffered and an unbuffered mode are available
* You can specify a maximum filesize
* You can specify a maximum age per directory

In buffered mode, the whole file is read into memory and only emitted if it passes some basic checks, like being UTF-8 and starting with an agent section.
In buffered mode also non-terminated piggyback sections will be correctly terminated.
In unbuffered mode, the file is just printed to STDOUT. Invalid UTF-8 will make the output stop within a file.

For configuration a JSON config file xtraspool.json must be present in `$MK_CONFDIR`.
See the comments in xtraspool.py to get an idea how to write on.
Users of the commercial editions can use the Agent Bakery to configure the plugin.

== Compatibility

Currently, Checkmk versions 2.3.0 to 2.5.0 are supported.

== Installation

=== Normal users

////
Download the MKP from the _Releases_ section (when it becomes available) and install as described in the link:https://docs.checkmk.com/latest/en/mkps.html[Official Checkmk User Guide].
////

No MKP added yet.
I will add an MKP when I am finished with error handling and creating a separate `xtraspool` service that tells about errors.

=== Developers

*Be careful, the paths in this repo might only work with Checkmk 2.4!*

Clone this repository, then sync the content of `_omd_root` to the root directory of your Checkmk site.
Then restart the site with `omd restart`.
After updating, it might be necessary to remove outdated `.pyc` files between stopping and starting the site.
